package replete.bash;

import replete.text.StringUtil;

public class VersionConstants {


    ///////////////
    // CONSTANTS //
    ///////////////

    // All of these numbers are changed when you execute
    // the Ant build script.  You change these numbers
    // by changing the numbers in the Ant build script
    // before you execute it.

    // ** DO NOT EDIT THIS FILE **

    // The following variables are set automatically by the build script.

    public static final String MAJOR   = "1";
    public static final String MINOR   = "0";
    public static final String SERVICE = "0";
    public static final String BUILD   = null;


    ////////////
    // FIELDS //
    ////////////

    // This variable can be set at runtime to provide an additional
    // version label for the overall version.  Examples:
    //   stable, rc, all_plugins, for_dave

    private static String label = null;


    //////////////////////////
    // ACCESSORS / MUTATORS //
    //////////////////////////

    // Accessor

    public static String getLabel() {
        return label;
    }

    // Mutator

    public static void setLabel(String label) {
        VersionConstants.label = label;
    }


    ///////////
    // LABEL //
    ///////////

    public static String getFullVersionString() {
        String version = MAJOR + "." + MINOR + "." + SERVICE;
        if(BUILD == null) {
            version += " (Development Build)";
        } else {
            version += " (" + BUILD + ")";
        }
        if(!StringUtil.isBlank(label)) {
            version += " [" + label + "]";
        }
        return version;
    }


    //////////
    // MISC //
    //////////

    public static boolean equalsIgnoringLabel(String otherFullVersionString) {
        String other = StringUtil.firstSegment(otherFullVersionString, " [");
        String mine = StringUtil.firstSegment(getFullVersionString(), " [");
        return other.equals(mine);
    }
}
